// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoFinal.Data;

namespace ProjetoFinal.Migrations
{
    [DbContext(typeof(ProjetoFinalContext))]
    [Migration("20211218023532_EntitiesChange")]
    partial class EntitiesChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoFinal.Models.Comprador", b =>
                {
                    b.Property<double>("Cpf")
                        .HasColumnType("double");

                    b.Property<string>("Primeiro_nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Telefone")
                        .HasColumnType("double");

                    b.HasKey("Cpf");

                    b.ToTable("Comprador");
                });

            modelBuilder.Entity("ProjetoFinal.Models.Loja", b =>
                {
                    b.Property<double>("Cnpj")
                        .HasColumnType("double");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Num_Vendas")
                        .HasColumnType("double");

                    b.HasKey("Cnpj");

                    b.ToTable("Loja");
                });

            modelBuilder.Entity("ProjetoFinal.Models.Usuario", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<double?>("CompradorCpf")
                        .HasColumnType("double");

                    b.Property<int>("Enumeracao")
                        .HasColumnType("int");

                    b.Property<double?>("LojaCnpj")
                        .HasColumnType("double");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Login");

                    b.HasIndex("CompradorCpf");

                    b.HasIndex("LojaCnpj");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ProjetoFinal.Models.Usuario", b =>
                {
                    b.HasOne("ProjetoFinal.Models.Comprador", null)
                        .WithMany("Comprador_usuario")
                        .HasForeignKey("CompradorCpf");

                    b.HasOne("ProjetoFinal.Models.Loja", null)
                        .WithMany("Loja_usuario")
                        .HasForeignKey("LojaCnpj");
                });
#pragma warning restore 612, 618
        }
    }
}
